name: Java Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, windows-latest]
        jdk_version: ['16']
        
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.jdk_version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk_version }}
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test
